apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app: customer
  namespace: harinvb
  annotations:
    monitoring: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      name: customer-app
      namespace: harinvb
      labels:
        app: customer
    spec:
      containers:
      - image: harinvb/customer:14
        name: customer
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"           